# # Fill in keys to run locally
# development:
#   bucket: urop-io
#   access_key_id: access_key_id
#   secret_access_key: secret_access_key
# test:
#   bucket: urop-io
#   access_key_id: access_key_id
#   secret_access_key: secret_access_key
# production:
#   bucket: urop-io
#   access_key_id: access_key_id
#   secret_access_key: secret_access_key


development:
  bucket: urop-io
  access_key_id: AKIAJVG4MPW2DYX6RWSQ
  secret_access_key: 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
test:
  bucket: urop-io
  access_key_id: AKIAJVG4MPW2DYX6RWSQ
  secret_access_key: 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
production:
  bucket: urop-io
  access_key_id: AKIAJVG4MPW2DYX6RWSQ
  secret_access_key: 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	
